/*
 * Created on 6 Dec 2015 ( Time 04:13:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.business.service;

import java.util.List;

import tristi.general.bean.Bank;

/**
 * Business Service Interface for entity Bank.
 */
public interface BankService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param bankid
	 * @return entity
	 */
	Bank findById( String bankid  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Bank> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Bank save(Bank entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Bank update(Bank entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Bank create(Bank entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param bankid
	 */
	void delete( String bankid );
	
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param bankid
	 * @return
	 */
	public boolean exists( String bankid ) ;
	
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;


}
