/*
 * Created on 6 Dec 2015 ( Time 04:13:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.business.service;

import java.util.List;

import tristi.general.bean.Category;

/**
 * Business Service Interface for entity Category.
 */
public interface CategoryService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param categoryid
	 * @return entity
	 */
	Category findById( String categoryid  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Category> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Category save(Category entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Category update(Category entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Category create(Category entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param categoryid
	 */
	void delete( String categoryid );
	
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param categoryid
	 * @return
	 */
	public boolean exists( String categoryid ) ;
	
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;


}
