/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.business.service;

import java.util.List;

import tristi.general.bean.Detailexpired;

/**
 * Business Service Interface for entity Detailexpired.
 */
public interface DetailexpiredService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param detailexpiredid
	 * @return entity
	 */
	Detailexpired findById( String detailexpiredid  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Detailexpired> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Detailexpired save(Detailexpired entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Detailexpired update(Detailexpired entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Detailexpired create(Detailexpired entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param detailexpiredid
	 */
	void delete( String detailexpiredid );
	
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param detailexpiredid
	 * @return
	 */
	public boolean exists( String detailexpiredid ) ;
	
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;


}
