/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.business.service;

import java.util.List;

import tristi.general.bean.Paymentform;

/**
 * Business Service Interface for entity Paymentform.
 */
public interface PaymentformService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param paymentformid
	 * @return entity
	 */
	Paymentform findById( String paymentformid  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Paymentform> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Paymentform save(Paymentform entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Paymentform update(Paymentform entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Paymentform create(Paymentform entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param paymentformid
	 */
	void delete( String paymentformid );
	
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param paymentformid
	 * @return
	 */
	public boolean exists( String paymentformid ) ;
	
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;


}
