/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.business.service;

import java.util.List;

import tristi.general.bean.Pricehistory;

/**
 * Business Service Interface for entity Pricehistory.
 */
public interface PricehistoryService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param pricehistoryid
	 * @return entity
	 */
	Pricehistory findById( String pricehistoryid  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Pricehistory> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Pricehistory save(Pricehistory entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Pricehistory update(Pricehistory entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Pricehistory create(Pricehistory entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param pricehistoryid
	 */
	void delete( String pricehistoryid );
	
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param pricehistoryid
	 * @return
	 */
	public boolean exists( String pricehistoryid ) ;
	
	/**
	 * Counts all the records present in the database table
	 * @return
	 */
	public long count() ;


}
