/*
 * Created on 10 Dec 2015 ( Time 04:32:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.business.service.jdbc.commons;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

//import org.springframework.context.annotation.AnnotationConfigApplicationContext;
//
//import tristi.general.business.service.jdbc.impl.spring.commons.SpringConfiguration;

/**
 * DAO instance provider
 * 
 *
 */
public class DAOProvider {

	private final static ApplicationContext applicationContext = new ClassPathXmlApplicationContext("META-INF/spring/applicationContext.xml");
//	private final static ApplicationContext applicationContext = new AnnotationConfigApplicationContext(SpringConfiguration.class);
	@Autowired
	static DataSource dataSource ;

	public final static <T> T getDAO(Class<T> clazz) {
		return applicationContext.getBean(clazz);
	}
	
	public final static DataSource getDataSource() {
		return dataSource;
	}
	
}
