/*
 * Created on 6 Dec 2015 ( Time 04:08:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package tristi.general.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;
import java.util.UUID;

import javax.persistence.*;
import org.hibernate.annotations.Type;

/**
 * Persistent class for entity stored in table "bank"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="bank", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="BankEntity.countAll", query="SELECT COUNT(x) FROM BankEntity x" )
} )
public class BankEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="bankid", nullable=false, length=255)
    @Type(type = "org.hibernate.type.PostgresUUIDType")
    private UUID     bankid       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="bankname", length=50)
    private String     bankname     ;

    @Column(name="bankdescription", length=100)
    private String     bankdescription ;

    @Column(name="bankisactive")
    private Boolean    bankisactive ;

    @Temporal(TemporalType.DATE)
    @Column(name="bankmoddate")
    private Date       bankmoddate  ;

	// "bankUserid" (column "bank_userid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="bank_userid", referencedColumnName="userid")
    private UseraccessEntity useraccess  ;

    @OneToMany(mappedBy="bank", targetEntity=AccountbankEntity.class)
    private List<AccountbankEntity> listOfAccountbank;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public BankEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setBankid( UUID bankid ) {
        this.bankid = bankid ;
    }
    public UUID getBankid() {
        return this.bankid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : bankname ( varchar ) 
    public void setBankname( String bankname ) {
        this.bankname = bankname;
    }
    public String getBankname() {
        return this.bankname;
    }

    //--- DATABASE MAPPING : bankdescription ( varchar ) 
    public void setBankdescription( String bankdescription ) {
        this.bankdescription = bankdescription;
    }
    public String getBankdescription() {
        return this.bankdescription;
    }

    //--- DATABASE MAPPING : bankisactive ( bool ) 
    public void setBankisactive( Boolean bankisactive ) {
        this.bankisactive = bankisactive;
    }
    public Boolean getBankisactive() {
        return this.bankisactive;
    }

    //--- DATABASE MAPPING : bankmoddate ( date ) 
    public void setBankmoddate( Date bankmoddate ) {
        this.bankmoddate = bankmoddate;
    }
    public Date getBankmoddate() {
        return this.bankmoddate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setUseraccess( UseraccessEntity useraccess ) {
        this.useraccess = useraccess;
    }
    public UseraccessEntity getUseraccess() {
        return this.useraccess;
    }

    public void setListOfAccountbank( List<AccountbankEntity> listOfAccountbank ) {
        this.listOfAccountbank = listOfAccountbank;
    }
    public List<AccountbankEntity> getListOfAccountbank() {
        return this.listOfAccountbank;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(bankid);
        sb.append("]:"); 
        sb.append(bankname);
        sb.append("|");
        sb.append(bankdescription);
        sb.append("|");
        sb.append(bankisactive);
        sb.append("|");
        sb.append(bankmoddate);
        return sb.toString(); 
    } 

}
