/*
 * Created on 6 Dec 2015 ( Time 04:08:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package tristi.general.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;
import java.util.UUID;

import javax.persistence.*;
import org.hibernate.annotations.Type;

/**
 * Persistent class for entity stored in table "category"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="category", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CategoryEntity.countAll", query="SELECT COUNT(x) FROM CategoryEntity x" )
} )
public class CategoryEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="categoryid", nullable=false, length=255)
    @Type(type = "org.hibernate.type.PostgresUUIDType")
    private UUID     categoryid   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="categorycode", length=50)
    private String     categorycode ;

    @Column(name="categoryname", length=100)
    private String     categoryname ;

    @Column(name="categoryisactive")
    private Boolean    categoryisactive ;

    @Temporal(TemporalType.DATE)
    @Column(name="categorymoddate")
    private Date       categorymoddate ;

	// "categoryUserid" (column "category_userid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="category", targetEntity=ProductEntity.class)
    private List<ProductEntity> listOfProduct;

    @ManyToOne
    @JoinColumn(name="category_userid", referencedColumnName="userid")
    private UseraccessEntity useraccess  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CategoryEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCategoryid( UUID categoryid ) {
        this.categoryid = categoryid ;
    }
    public UUID getCategoryid() {
        return this.categoryid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : categorycode ( varchar ) 
    public void setCategorycode( String categorycode ) {
        this.categorycode = categorycode;
    }
    public String getCategorycode() {
        return this.categorycode;
    }

    //--- DATABASE MAPPING : categoryname ( varchar ) 
    public void setCategoryname( String categoryname ) {
        this.categoryname = categoryname;
    }
    public String getCategoryname() {
        return this.categoryname;
    }

    //--- DATABASE MAPPING : categoryisactive ( bool ) 
    public void setCategoryisactive( Boolean categoryisactive ) {
        this.categoryisactive = categoryisactive;
    }
    public Boolean getCategoryisactive() {
        return this.categoryisactive;
    }

    //--- DATABASE MAPPING : categorymoddate ( date ) 
    public void setCategorymoddate( Date categorymoddate ) {
        this.categorymoddate = categorymoddate;
    }
    public Date getCategorymoddate() {
        return this.categorymoddate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfProduct( List<ProductEntity> listOfProduct ) {
        this.listOfProduct = listOfProduct;
    }
    public List<ProductEntity> getListOfProduct() {
        return this.listOfProduct;
    }

    public void setUseraccess( UseraccessEntity useraccess ) {
        this.useraccess = useraccess;
    }
    public UseraccessEntity getUseraccess() {
        return this.useraccess;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(categoryid);
        sb.append("]:"); 
        sb.append(categorycode);
        sb.append("|");
        sb.append(categoryname);
        sb.append("|");
        sb.append(categoryisactive);
        sb.append("|");
        sb.append(categorymoddate);
        return sb.toString(); 
    } 

}
