/*
 * Created on 6 Dec 2015 ( Time 04:08:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package tristi.general.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.UUID;

import javax.persistence.*;
import org.hibernate.annotations.Type;

/**
 * Persistent class for entity stored in table "purchaseorderdtl"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="purchaseorderdtl", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PurchaseorderdtlEntity.countAll", query="SELECT COUNT(x) FROM PurchaseorderdtlEntity x" )
} )
public class PurchaseorderdtlEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="purchaseorderdtlid", nullable=false, length=255)
    @Type(type = "org.hibernate.type.PostgresUUIDType")
    private UUID     purchaseorderdtlid ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="purchaseorderdtlqty")
    private Integer    purchaseorderdtlqty ;

    @Column(name="purchaseorderdtlremainingqty")
    private Integer    purchaseorderdtlremainingqty ;

    @Column(name="purchaseorderdtlprice")
    private Double     purchaseorderdtlprice ;

    @Column(name="purchaseorderdtldiscount")
    private Double     purchaseorderdtldiscount ;

    @Temporal(TemporalType.DATE)
    @Column(name="purchaseorderdtlmoddate")
    private Date       purchaseorderdtlmoddate ;

	// "podtlPoid" (column "podtl_poid") is not defined by itself because used as FK in a link 
	// "podtlProductuomid" (column "podtl_productuomid") is not defined by itself because used as FK in a link 
	// "podtlUserid" (column "podtl_userid") is not defined by itself because used as FK in a link 
	// "podtlDetailexpiredid" (column "podtl_detailexpiredid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="podtl_poid", referencedColumnName="purchaseorderid")
    private PurchaseorderEntity purchaseorder;

    @ManyToOne
    @JoinColumn(name="podtl_detailexpiredid", referencedColumnName="detailexpiredid")
    private DetailexpiredEntity detailexpired;

    @ManyToOne
    @JoinColumn(name="podtl_productuomid", referencedColumnName="productuomid")
    private ProductuomEntity productuom  ;

    @ManyToOne
    @JoinColumn(name="podtl_userid", referencedColumnName="userid")
    private UseraccessEntity useraccess  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PurchaseorderdtlEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPurchaseorderdtlid( UUID purchaseorderdtlid ) {
        this.purchaseorderdtlid = purchaseorderdtlid ;
    }
    public UUID getPurchaseorderdtlid() {
        return this.purchaseorderdtlid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : purchaseorderdtlqty ( int4 ) 
    public void setPurchaseorderdtlqty( Integer purchaseorderdtlqty ) {
        this.purchaseorderdtlqty = purchaseorderdtlqty;
    }
    public Integer getPurchaseorderdtlqty() {
        return this.purchaseorderdtlqty;
    }

    //--- DATABASE MAPPING : purchaseorderdtlremainingqty ( int4 ) 
    public void setPurchaseorderdtlremainingqty( Integer purchaseorderdtlremainingqty ) {
        this.purchaseorderdtlremainingqty = purchaseorderdtlremainingqty;
    }
    public Integer getPurchaseorderdtlremainingqty() {
        return this.purchaseorderdtlremainingqty;
    }

    //--- DATABASE MAPPING : purchaseorderdtlprice ( float8 ) 
    public void setPurchaseorderdtlprice( Double purchaseorderdtlprice ) {
        this.purchaseorderdtlprice = purchaseorderdtlprice;
    }
    public Double getPurchaseorderdtlprice() {
        return this.purchaseorderdtlprice;
    }

    //--- DATABASE MAPPING : purchaseorderdtldiscount ( float8 ) 
    public void setPurchaseorderdtldiscount( Double purchaseorderdtldiscount ) {
        this.purchaseorderdtldiscount = purchaseorderdtldiscount;
    }
    public Double getPurchaseorderdtldiscount() {
        return this.purchaseorderdtldiscount;
    }

    //--- DATABASE MAPPING : purchaseorderdtlmoddate ( date ) 
    public void setPurchaseorderdtlmoddate( Date purchaseorderdtlmoddate ) {
        this.purchaseorderdtlmoddate = purchaseorderdtlmoddate;
    }
    public Date getPurchaseorderdtlmoddate() {
        return this.purchaseorderdtlmoddate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setPurchaseorder( PurchaseorderEntity purchaseorder ) {
        this.purchaseorder = purchaseorder;
    }
    public PurchaseorderEntity getPurchaseorder() {
        return this.purchaseorder;
    }

    public void setDetailexpired( DetailexpiredEntity detailexpired ) {
        this.detailexpired = detailexpired;
    }
    public DetailexpiredEntity getDetailexpired() {
        return this.detailexpired;
    }

    public void setProductuom( ProductuomEntity productuom ) {
        this.productuom = productuom;
    }
    public ProductuomEntity getProductuom() {
        return this.productuom;
    }

    public void setUseraccess( UseraccessEntity useraccess ) {
        this.useraccess = useraccess;
    }
    public UseraccessEntity getUseraccess() {
        return this.useraccess;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(purchaseorderdtlid);
        sb.append("]:"); 
        sb.append(purchaseorderdtlqty);
        sb.append("|");
        sb.append(purchaseorderdtlremainingqty);
        sb.append("|");
        sb.append(purchaseorderdtlprice);
        sb.append("|");
        sb.append(purchaseorderdtldiscount);
        sb.append("|");
        sb.append(purchaseorderdtlmoddate);
        return sb.toString(); 
    } 

}
