/*
 * Created on 6 Dec 2015 ( Time 04:08:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package tristi.general.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;
import java.util.UUID;

import javax.persistence.*;
import org.hibernate.annotations.Type;

/**
 * Persistent class for entity stored in table "returnsupplier"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="returnsupplier", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ReturnsupplierEntity.countAll", query="SELECT COUNT(x) FROM ReturnsupplierEntity x" )
} )
public class ReturnsupplierEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="returnsupplierid", nullable=false, length=255)
    @Type(type = "org.hibernate.type.PostgresUUIDType")
    private UUID     returnsupplierid ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="returnsupplier_userid", length=255)
    private String     returnsupplierUserid ;

    @Column(name="returnsuppliercode", length=50)
    private String     returnsuppliercode ;

    @Temporal(TemporalType.DATE)
    @Column(name="returnsupplierdate")
    private Date       returnsupplierdate ;

    @Column(name="returnsupplieramount")
    private Double     returnsupplieramount ;

    @Column(name="returnsupplierstatus", length=50)
    private String     returnsupplierstatus ;

    @Temporal(TemporalType.DATE)
    @Column(name="returnsuppliermoddate")
    private Date       returnsuppliermoddate ;

	// "returnsupplierSupplierid" (column "returnsupplier_supplierid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="returnsupplier", targetEntity=ReturnsupplierdtlEntity.class)
    private List<ReturnsupplierdtlEntity> listOfReturnsupplierdtl;

    @ManyToOne
    @JoinColumn(name="returnsupplier_supplierid", referencedColumnName="supplierid")
    private SupplierEntity supplier    ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ReturnsupplierEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setReturnsupplierid( UUID returnsupplierid ) {
        this.returnsupplierid = returnsupplierid ;
    }
    public UUID getReturnsupplierid() {
        return this.returnsupplierid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : returnsupplier_userid ( varchar ) 
    public void setReturnsupplierUserid( String returnsupplierUserid ) {
        this.returnsupplierUserid = returnsupplierUserid;
    }
    public String getReturnsupplierUserid() {
        return this.returnsupplierUserid;
    }

    //--- DATABASE MAPPING : returnsuppliercode ( varchar ) 
    public void setReturnsuppliercode( String returnsuppliercode ) {
        this.returnsuppliercode = returnsuppliercode;
    }
    public String getReturnsuppliercode() {
        return this.returnsuppliercode;
    }

    //--- DATABASE MAPPING : returnsupplierdate ( date ) 
    public void setReturnsupplierdate( Date returnsupplierdate ) {
        this.returnsupplierdate = returnsupplierdate;
    }
    public Date getReturnsupplierdate() {
        return this.returnsupplierdate;
    }

    //--- DATABASE MAPPING : returnsupplieramount ( float8 ) 
    public void setReturnsupplieramount( Double returnsupplieramount ) {
        this.returnsupplieramount = returnsupplieramount;
    }
    public Double getReturnsupplieramount() {
        return this.returnsupplieramount;
    }

    //--- DATABASE MAPPING : returnsupplierstatus ( varchar ) 
    public void setReturnsupplierstatus( String returnsupplierstatus ) {
        this.returnsupplierstatus = returnsupplierstatus;
    }
    public String getReturnsupplierstatus() {
        return this.returnsupplierstatus;
    }

    //--- DATABASE MAPPING : returnsuppliermoddate ( date ) 
    public void setReturnsuppliermoddate( Date returnsuppliermoddate ) {
        this.returnsuppliermoddate = returnsuppliermoddate;
    }
    public Date getReturnsuppliermoddate() {
        return this.returnsuppliermoddate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfReturnsupplierdtl( List<ReturnsupplierdtlEntity> listOfReturnsupplierdtl ) {
        this.listOfReturnsupplierdtl = listOfReturnsupplierdtl;
    }
    public List<ReturnsupplierdtlEntity> getListOfReturnsupplierdtl() {
        return this.listOfReturnsupplierdtl;
    }

    public void setSupplier( SupplierEntity supplier ) {
        this.supplier = supplier;
    }
    public SupplierEntity getSupplier() {
        return this.supplier;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(returnsupplierid);
        sb.append("]:"); 
        sb.append(returnsupplierUserid);
        sb.append("|");
        sb.append(returnsuppliercode);
        sb.append("|");
        sb.append(returnsupplierdate);
        sb.append("|");
        sb.append(returnsupplieramount);
        sb.append("|");
        sb.append(returnsupplierstatus);
        sb.append("|");
        sb.append(returnsuppliermoddate);
        return sb.toString(); 
    } 

}
