/*
 * Created on 6 Dec 2015 ( Time 04:08:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package tristi.general.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.UUID;

import javax.persistence.*;
import org.hibernate.annotations.Type;

/**
 * Persistent class for entity stored in table "salesordercorrection"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="salesordercorrection", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SalesordercorrectionEntity.countAll", query="SELECT COUNT(x) FROM SalesordercorrectionEntity x" )
} )
public class SalesordercorrectionEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="salesordercorrectionid", nullable=false, length=255)
    @Type(type = "org.hibernate.type.PostgresUUIDType")
    private UUID     salesordercorrectionid ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="salesordercorrection_sodtlid", length=255)
    private String     salesordercorrectionSodtlid ;

    @Column(name="salesordercorrection_userid", length=255)
    private String     salesordercorrectionUserid ;

    @Column(name="salesordercorrectionqty")
    private Integer    salesordercorrectionqty ;

    @Column(name="salesordercorrectionprice")
    private Double     salesordercorrectionprice ;

    @Column(name="salesordercorrectionbaseprice")
    private Double     salesordercorrectionbaseprice ;

    @Column(name="salesordercorrectiondiscount")
    private Double     salesordercorrectiondiscount ;

    @Temporal(TemporalType.DATE)
    @Column(name="salesordercorrectionmoddate")
    private Date       salesordercorrectionmoddate ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SalesordercorrectionEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSalesordercorrectionid( UUID salesordercorrectionid ) {
        this.salesordercorrectionid = salesordercorrectionid ;
    }
    public UUID getSalesordercorrectionid() {
        return this.salesordercorrectionid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : salesordercorrection_sodtlid ( varchar ) 
    public void setSalesordercorrectionSodtlid( String salesordercorrectionSodtlid ) {
        this.salesordercorrectionSodtlid = salesordercorrectionSodtlid;
    }
    public String getSalesordercorrectionSodtlid() {
        return this.salesordercorrectionSodtlid;
    }

    //--- DATABASE MAPPING : salesordercorrection_userid ( varchar ) 
    public void setSalesordercorrectionUserid( String salesordercorrectionUserid ) {
        this.salesordercorrectionUserid = salesordercorrectionUserid;
    }
    public String getSalesordercorrectionUserid() {
        return this.salesordercorrectionUserid;
    }

    //--- DATABASE MAPPING : salesordercorrectionqty ( int4 ) 
    public void setSalesordercorrectionqty( Integer salesordercorrectionqty ) {
        this.salesordercorrectionqty = salesordercorrectionqty;
    }
    public Integer getSalesordercorrectionqty() {
        return this.salesordercorrectionqty;
    }

    //--- DATABASE MAPPING : salesordercorrectionprice ( float8 ) 
    public void setSalesordercorrectionprice( Double salesordercorrectionprice ) {
        this.salesordercorrectionprice = salesordercorrectionprice;
    }
    public Double getSalesordercorrectionprice() {
        return this.salesordercorrectionprice;
    }

    //--- DATABASE MAPPING : salesordercorrectionbaseprice ( float8 ) 
    public void setSalesordercorrectionbaseprice( Double salesordercorrectionbaseprice ) {
        this.salesordercorrectionbaseprice = salesordercorrectionbaseprice;
    }
    public Double getSalesordercorrectionbaseprice() {
        return this.salesordercorrectionbaseprice;
    }

    //--- DATABASE MAPPING : salesordercorrectiondiscount ( float8 ) 
    public void setSalesordercorrectiondiscount( Double salesordercorrectiondiscount ) {
        this.salesordercorrectiondiscount = salesordercorrectiondiscount;
    }
    public Double getSalesordercorrectiondiscount() {
        return this.salesordercorrectiondiscount;
    }

    //--- DATABASE MAPPING : salesordercorrectionmoddate ( date ) 
    public void setSalesordercorrectionmoddate( Date salesordercorrectionmoddate ) {
        this.salesordercorrectionmoddate = salesordercorrectionmoddate;
    }
    public Date getSalesordercorrectionmoddate() {
        return this.salesordercorrectionmoddate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(salesordercorrectionid);
        sb.append("]:"); 
        sb.append(salesordercorrectionSodtlid);
        sb.append("|");
        sb.append(salesordercorrectionUserid);
        sb.append("|");
        sb.append(salesordercorrectionqty);
        sb.append("|");
        sb.append(salesordercorrectionprice);
        sb.append("|");
        sb.append(salesordercorrectionbaseprice);
        sb.append("|");
        sb.append(salesordercorrectiondiscount);
        sb.append("|");
        sb.append(salesordercorrectionmoddate);
        return sb.toString(); 
    } 

}
