/*
 * Created on 6 Dec 2015 ( Time 04:08:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package tristi.general.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.UUID;

import javax.persistence.*;
import org.hibernate.annotations.Type;

/**
 * Persistent class for entity stored in table "salesorderdtl"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="salesorderdtl", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SalesorderdtlEntity.countAll", query="SELECT COUNT(x) FROM SalesorderdtlEntity x" )
} )
public class SalesorderdtlEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="salesorderdtlid", nullable=false, length=255)
    @Type(type = "org.hibernate.type.PostgresUUIDType")
    private UUID     salesorderdtlid ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="salesorderdtlqty")
    private Integer    salesorderdtlqty ;

    @Column(name="salesorderdtlremainingqty")
    private Integer    salesorderdtlremainingqty ;

    @Column(name="salesorderdtlprice")
    private Double     salesorderdtlprice ;

    @Column(name="salesorderdtlbaseprice")
    private Double     salesorderdtlbaseprice ;

    @Column(name="salesorderdtldiscount")
    private Double     salesorderdtldiscount ;

    @Column(name="salesorderdtlstatus", length=50)
    private String     salesorderdtlstatus ;

    @Temporal(TemporalType.DATE)
    @Column(name="salesorderdtlmoddate")
    private Date       salesorderdtlmoddate ;

	// "salesorderid" (column "salesorderid") is not defined by itself because used as FK in a link 
	// "detailexpiredid" (column "detailexpiredid") is not defined by itself because used as FK in a link 
	// "userid" (column "userid") is not defined by itself because used as FK in a link 
	// "productuomid" (column "productuomid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="sodtl_userid", referencedColumnName="userid")
    private UseraccessEntity useraccess  ;

    @ManyToOne
    @JoinColumn(name="sodtl_detailexpiredid", referencedColumnName="detailexpiredid")
    private DetailexpiredEntity detailexpired;

    @ManyToOne
    @JoinColumn(name="sodtl_productuomid", referencedColumnName="productuomid")
    private ProductuomEntity productuom  ;

    @ManyToOne
    @JoinColumn(name="sodtl_salesorderid", referencedColumnName="salesorderid")
    private SalesorderEntity salesorder  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SalesorderdtlEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSalesorderdtlid( UUID salesorderdtlid ) {
        this.salesorderdtlid = salesorderdtlid ;
    }
    public UUID getSalesorderdtlid() {
        return this.salesorderdtlid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : salesorderdtlqty ( int4 ) 
    public void setSalesorderdtlqty( Integer salesorderdtlqty ) {
        this.salesorderdtlqty = salesorderdtlqty;
    }
    public Integer getSalesorderdtlqty() {
        return this.salesorderdtlqty;
    }

    //--- DATABASE MAPPING : salesorderdtlremainingqty ( int4 ) 
    public void setSalesorderdtlremainingqty( Integer salesorderdtlremainingqty ) {
        this.salesorderdtlremainingqty = salesorderdtlremainingqty;
    }
    public Integer getSalesorderdtlremainingqty() {
        return this.salesorderdtlremainingqty;
    }

    //--- DATABASE MAPPING : salesorderdtlprice ( float8 ) 
    public void setSalesorderdtlprice( Double salesorderdtlprice ) {
        this.salesorderdtlprice = salesorderdtlprice;
    }
    public Double getSalesorderdtlprice() {
        return this.salesorderdtlprice;
    }

    //--- DATABASE MAPPING : salesorderdtlbaseprice ( float8 ) 
    public void setSalesorderdtlbaseprice( Double salesorderdtlbaseprice ) {
        this.salesorderdtlbaseprice = salesorderdtlbaseprice;
    }
    public Double getSalesorderdtlbaseprice() {
        return this.salesorderdtlbaseprice;
    }

    //--- DATABASE MAPPING : salesorderdtldiscount ( float8 ) 
    public void setSalesorderdtldiscount( Double salesorderdtldiscount ) {
        this.salesorderdtldiscount = salesorderdtldiscount;
    }
    public Double getSalesorderdtldiscount() {
        return this.salesorderdtldiscount;
    }

    //--- DATABASE MAPPING : salesorderdtlstatus ( varchar ) 
    public void setSalesorderdtlstatus( String salesorderdtlstatus ) {
        this.salesorderdtlstatus = salesorderdtlstatus;
    }
    public String getSalesorderdtlstatus() {
        return this.salesorderdtlstatus;
    }

    //--- DATABASE MAPPING : salesorderdtlmoddate ( date ) 
    public void setSalesorderdtlmoddate( Date salesorderdtlmoddate ) {
        this.salesorderdtlmoddate = salesorderdtlmoddate;
    }
    public Date getSalesorderdtlmoddate() {
        return this.salesorderdtlmoddate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setUseraccess( UseraccessEntity useraccess ) {
        this.useraccess = useraccess;
    }
    public UseraccessEntity getUseraccess() {
        return this.useraccess;
    }

    public void setDetailexpired( DetailexpiredEntity detailexpired ) {
        this.detailexpired = detailexpired;
    }
    public DetailexpiredEntity getDetailexpired() {
        return this.detailexpired;
    }

    public void setProductuom( ProductuomEntity productuom ) {
        this.productuom = productuom;
    }
    public ProductuomEntity getProductuom() {
        return this.productuom;
    }

    public void setSalesorder( SalesorderEntity salesorder ) {
        this.salesorder = salesorder;
    }
    public SalesorderEntity getSalesorder() {
        return this.salesorder;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(salesorderdtlid);
        sb.append("]:"); 
        sb.append(salesorderdtlqty);
        sb.append("|");
        sb.append(salesorderdtlremainingqty);
        sb.append("|");
        sb.append(salesorderdtlprice);
        sb.append("|");
        sb.append(salesorderdtlbaseprice);
        sb.append("|");
        sb.append(salesorderdtldiscount);
        sb.append("|");
        sb.append(salesorderdtlstatus);
        sb.append("|");
        sb.append(salesorderdtlmoddate);
        return sb.toString(); 
    } 

}
