/*
 * Created on 6 Dec 2015 ( Time 04:08:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package tristi.general.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;
import java.util.UUID;

import javax.persistence.*;
import org.hibernate.annotations.Type;

/**
 * Persistent class for entity stored in table "uom"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="uom", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="UomEntity.countAll", query="SELECT COUNT(x) FROM UomEntity x" )
} )
public class UomEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="uomid", nullable=false, length=255)
    @Type(type = "org.hibernate.type.PostgresUUIDType")
    private UUID     uomid        ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="uomcode", length=10)
    private String     uomcode      ;

    @Column(name="uomdescription", length=100)
    private String     uomdescription ;

    @Column(name="uomisactive")
    private Boolean    uomisactive  ;

    @Temporal(TemporalType.DATE)
    @Column(name="uommoddate")
    private Date       uommoddate   ;

	// "uomUserid" (column "uom_userid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="uom", targetEntity=ProductuomEntity.class)
    private List<ProductuomEntity> listOfProductuom;

    @ManyToOne
    @JoinColumn(name="uom_userid", referencedColumnName="userid")
    private UseraccessEntity useraccess  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public UomEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUomid( UUID uomid ) {
        this.uomid = uomid ;
    }
    public UUID getUomid() {
        return this.uomid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : uomcode ( varchar ) 
    public void setUomcode( String uomcode ) {
        this.uomcode = uomcode;
    }
    public String getUomcode() {
        return this.uomcode;
    }

    //--- DATABASE MAPPING : uomdescription ( varchar ) 
    public void setUomdescription( String uomdescription ) {
        this.uomdescription = uomdescription;
    }
    public String getUomdescription() {
        return this.uomdescription;
    }

    //--- DATABASE MAPPING : uomisactive ( bool ) 
    public void setUomisactive( Boolean uomisactive ) {
        this.uomisactive = uomisactive;
    }
    public Boolean getUomisactive() {
        return this.uomisactive;
    }

    //--- DATABASE MAPPING : uommoddate ( date ) 
    public void setUommoddate( Date uommoddate ) {
        this.uommoddate = uommoddate;
    }
    public Date getUommoddate() {
        return this.uommoddate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfProductuom( List<ProductuomEntity> listOfProductuom ) {
        this.listOfProductuom = listOfProductuom;
    }
    public List<ProductuomEntity> getListOfProductuom() {
        return this.listOfProductuom;
    }

    public void setUseraccess( UseraccessEntity useraccess ) {
        this.useraccess = useraccess;
    }
    public UseraccessEntity getUseraccess() {
        return this.useraccess;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(uomid);
        sb.append("]:"); 
        sb.append(uomcode);
        sb.append("|");
        sb.append(uomdescription);
        sb.append("|");
        sb.append(uomisactive);
        sb.append("|");
        sb.append(uommoddate);
        return sb.toString(); 
    } 

}
