/*
 * Created on 6 Dec 2015 ( Time 04:08:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package tristi.general.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;
import java.util.UUID;

import javax.persistence.*;
import org.hibernate.annotations.Type;

/**
 * Persistent class for entity stored in table "useraccess"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="useraccess", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="UseraccessEntity.countAll", query="SELECT COUNT(x) FROM UseraccessEntity x" )
} )
public class UseraccessEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="userid", nullable=false, length=255)
    @Type(type = "org.hibernate.type.PostgresUUIDType")
    private UUID     userid       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="usercode", length=100)
    private String     usercode     ;

    @Column(name="username", length=100)
    private String     username     ;

    @Temporal(TemporalType.DATE)
    @Column(name="usermoddate")
    private Date       usermoddate  ;

	// "userUserid" (column "user_userid") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="user_userid", referencedColumnName="userid")
    private UseraccessEntity useraccess  ;

    @OneToMany(mappedBy="useraccess", targetEntity=TypeEntity.class)
    private List<TypeEntity> listOfType  ;

    @OneToMany(mappedBy="useraccess", targetEntity=UseraccessEntity.class)
    private List<UseraccessEntity> listOfUseraccess;

    @OneToMany(mappedBy="useraccess", targetEntity=CategoryEntity.class)
    private List<CategoryEntity> listOfCategory;

    @OneToMany(mappedBy="useraccess", targetEntity=ProductEntity.class)
    private List<ProductEntity> listOfProduct;

    @OneToMany(mappedBy="useraccess", targetEntity=ProductuomEntity.class)
    private List<ProductuomEntity> listOfProductuom;

    @OneToMany(mappedBy="useraccess", targetEntity=PaymentformEntity.class)
    private List<PaymentformEntity> listOfPaymentform;

    @OneToMany(mappedBy="useraccess", targetEntity=PricehistoryEntity.class)
    private List<PricehistoryEntity> listOfPricehistory;

    @OneToMany(mappedBy="useraccess", targetEntity=AccountbankEntity.class)
    private List<AccountbankEntity> listOfAccountbank;

    @OneToMany(mappedBy="useraccess", targetEntity=LocationdtlEntity.class)
    private List<LocationdtlEntity> listOfLocationdtl;

    @OneToMany(mappedBy="useraccess", targetEntity=LocationEntity.class)
    private List<LocationEntity> listOfLocation;

    @OneToMany(mappedBy="useraccess", targetEntity=ProductstockEntity.class)
    private List<ProductstockEntity> listOfProductstock;

    @OneToMany(mappedBy="useraccess", targetEntity=SalesorderdtlEntity.class)
    private List<SalesorderdtlEntity> listOfSalesorderdtl;

    @OneToMany(mappedBy="useraccess", targetEntity=BankEntity.class)
    private List<BankEntity> listOfBank  ;

    @OneToMany(mappedBy="useraccess", targetEntity=UomEntity.class)
    private List<UomEntity> listOfUom   ;

    @OneToMany(mappedBy="useraccess", targetEntity=PurchaseorderdtlEntity.class)
    private List<PurchaseorderdtlEntity> listOfPurchaseorderdtl;

    @OneToMany(mappedBy="useraccess", targetEntity=ReturnsupplierdtlEntity.class)
    private List<ReturnsupplierdtlEntity> listOfReturnsupplierdtl;

    @OneToMany(mappedBy="useraccess", targetEntity=DetailexpiredEntity.class)
    private List<DetailexpiredEntity> listOfDetailexpired;

    @OneToMany(mappedBy="useraccess", targetEntity=SupplierproductEntity.class)
    private List<SupplierproductEntity> listOfSupplierproduct;

    @OneToMany(mappedBy="useraccess", targetEntity=SupplierEntity.class)
    private List<SupplierEntity> listOfSupplier;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public UseraccessEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUserid( UUID userid ) {
        this.userid = userid ;
    }
    public UUID getUserid() {
        return this.userid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : usercode ( varchar ) 
    public void setUsercode( String usercode ) {
        this.usercode = usercode;
    }
    public String getUsercode() {
        return this.usercode;
    }

    //--- DATABASE MAPPING : username ( varchar ) 
    public void setUsername( String username ) {
        this.username = username;
    }
    public String getUsername() {
        return this.username;
    }

    //--- DATABASE MAPPING : usermoddate ( date ) 
    public void setUsermoddate( Date usermoddate ) {
        this.usermoddate = usermoddate;
    }
    public Date getUsermoddate() {
        return this.usermoddate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setUseraccess( UseraccessEntity useraccess ) {
        this.useraccess = useraccess;
    }
    public UseraccessEntity getUseraccess() {
        return this.useraccess;
    }

    public void setListOfType( List<TypeEntity> listOfType ) {
        this.listOfType = listOfType;
    }
    public List<TypeEntity> getListOfType() {
        return this.listOfType;
    }

    public void setListOfUseraccess( List<UseraccessEntity> listOfUseraccess ) {
        this.listOfUseraccess = listOfUseraccess;
    }
    public List<UseraccessEntity> getListOfUseraccess() {
        return this.listOfUseraccess;
    }

    public void setListOfCategory( List<CategoryEntity> listOfCategory ) {
        this.listOfCategory = listOfCategory;
    }
    public List<CategoryEntity> getListOfCategory() {
        return this.listOfCategory;
    }

    public void setListOfProduct( List<ProductEntity> listOfProduct ) {
        this.listOfProduct = listOfProduct;
    }
    public List<ProductEntity> getListOfProduct() {
        return this.listOfProduct;
    }

    public void setListOfProductuom( List<ProductuomEntity> listOfProductuom ) {
        this.listOfProductuom = listOfProductuom;
    }
    public List<ProductuomEntity> getListOfProductuom() {
        return this.listOfProductuom;
    }

    public void setListOfPaymentform( List<PaymentformEntity> listOfPaymentform ) {
        this.listOfPaymentform = listOfPaymentform;
    }
    public List<PaymentformEntity> getListOfPaymentform() {
        return this.listOfPaymentform;
    }

    public void setListOfPricehistory( List<PricehistoryEntity> listOfPricehistory ) {
        this.listOfPricehistory = listOfPricehistory;
    }
    public List<PricehistoryEntity> getListOfPricehistory() {
        return this.listOfPricehistory;
    }

    public void setListOfAccountbank( List<AccountbankEntity> listOfAccountbank ) {
        this.listOfAccountbank = listOfAccountbank;
    }
    public List<AccountbankEntity> getListOfAccountbank() {
        return this.listOfAccountbank;
    }

    public void setListOfLocationdtl( List<LocationdtlEntity> listOfLocationdtl ) {
        this.listOfLocationdtl = listOfLocationdtl;
    }
    public List<LocationdtlEntity> getListOfLocationdtl() {
        return this.listOfLocationdtl;
    }

    public void setListOfLocation( List<LocationEntity> listOfLocation ) {
        this.listOfLocation = listOfLocation;
    }
    public List<LocationEntity> getListOfLocation() {
        return this.listOfLocation;
    }

    public void setListOfProductstock( List<ProductstockEntity> listOfProductstock ) {
        this.listOfProductstock = listOfProductstock;
    }
    public List<ProductstockEntity> getListOfProductstock() {
        return this.listOfProductstock;
    }

    public void setListOfSalesorderdtl( List<SalesorderdtlEntity> listOfSalesorderdtl ) {
        this.listOfSalesorderdtl = listOfSalesorderdtl;
    }
    public List<SalesorderdtlEntity> getListOfSalesorderdtl() {
        return this.listOfSalesorderdtl;
    }

    public void setListOfBank( List<BankEntity> listOfBank ) {
        this.listOfBank = listOfBank;
    }
    public List<BankEntity> getListOfBank() {
        return this.listOfBank;
    }

    public void setListOfUom( List<UomEntity> listOfUom ) {
        this.listOfUom = listOfUom;
    }
    public List<UomEntity> getListOfUom() {
        return this.listOfUom;
    }

    public void setListOfPurchaseorderdtl( List<PurchaseorderdtlEntity> listOfPurchaseorderdtl ) {
        this.listOfPurchaseorderdtl = listOfPurchaseorderdtl;
    }
    public List<PurchaseorderdtlEntity> getListOfPurchaseorderdtl() {
        return this.listOfPurchaseorderdtl;
    }

    public void setListOfReturnsupplierdtl( List<ReturnsupplierdtlEntity> listOfReturnsupplierdtl ) {
        this.listOfReturnsupplierdtl = listOfReturnsupplierdtl;
    }
    public List<ReturnsupplierdtlEntity> getListOfReturnsupplierdtl() {
        return this.listOfReturnsupplierdtl;
    }

    public void setListOfDetailexpired( List<DetailexpiredEntity> listOfDetailexpired ) {
        this.listOfDetailexpired = listOfDetailexpired;
    }
    public List<DetailexpiredEntity> getListOfDetailexpired() {
        return this.listOfDetailexpired;
    }

    public void setListOfSupplierproduct( List<SupplierproductEntity> listOfSupplierproduct ) {
        this.listOfSupplierproduct = listOfSupplierproduct;
    }
    public List<SupplierproductEntity> getListOfSupplierproduct() {
        return this.listOfSupplierproduct;
    }

    public void setListOfSupplier( List<SupplierEntity> listOfSupplier ) {
        this.listOfSupplier = listOfSupplier;
    }
    public List<SupplierEntity> getListOfSupplier() {
        return this.listOfSupplier;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(userid);
        sb.append("]:"); 
        sb.append(usercode);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(usermoddate);
        return sb.toString(); 
    } 

}
