/*
 * Created on 6 Dec 2015 ( Time 04:08:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.business.service.impl;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.ArrayList;
import java.util.List;

import tristi.general.bean.Type;
import tristi.general.bean.jpa.TypeEntity;

import java.util.Date;
import java.util.List;

import tristi.general.business.service.jpa.impl.TypeServiceImpl;
import tristi.general.business.service.jpa.mapping.TypeServiceMapper;
import tristi.general.data.repository.jpa.TypeJpaRepository;
import tristi.general.test.TypeFactoryForTest;
import tristi.general.test.TypeEntityFactoryForTest;
import tristi.general.test.MockValues;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

/**
 * Test : Implementation of TypeService
 */
@RunWith(MockitoJUnitRunner.class)
public class TypeServiceImplTest {

	@InjectMocks
	private TypeServiceImpl typeService;
	@Mock
	private TypeJpaRepository typeJpaRepository;
	@Mock
	private TypeServiceMapper typeServiceMapper;
	
	private TypeFactoryForTest typeFactoryForTest = new TypeFactoryForTest();

	private TypeEntityFactoryForTest typeEntityFactoryForTest = new TypeEntityFactoryForTest();

	private MockValues mockValues = new MockValues();
	
	@Test
	public void findById() {
		// Given
		String typeid = mockValues.nextString(255);
		
		TypeEntity typeEntity = typeJpaRepository.findOne(typeid);
		
		Type type = typeFactoryForTest.newType();
		when(typeServiceMapper.mapTypeEntityToType(typeEntity)).thenReturn(type);

		// When
		Type typeFound = typeService.findById(typeid);

		// Then
		assertEquals(type.getTypeid(),typeFound.getTypeid());
	}

	@Test
	public void findAll() {
		// Given
		List<TypeEntity> typeEntitys = new ArrayList<TypeEntity>();
		TypeEntity typeEntity1 = typeEntityFactoryForTest.newTypeEntity();
		typeEntitys.add(typeEntity1);
		TypeEntity typeEntity2 = typeEntityFactoryForTest.newTypeEntity();
		typeEntitys.add(typeEntity2);
		when(typeJpaRepository.findAll()).thenReturn(typeEntitys);
		
		Type type1 = typeFactoryForTest.newType();
		when(typeServiceMapper.mapTypeEntityToType(typeEntity1)).thenReturn(type1);
		Type type2 = typeFactoryForTest.newType();
		when(typeServiceMapper.mapTypeEntityToType(typeEntity2)).thenReturn(type2);

		// When
		List<Type> typesFounds = typeService.findAll();

		// Then
		assertTrue(type1 == typesFounds.get(0));
		assertTrue(type2 == typesFounds.get(1));
	}

	@Test
	public void create() {
		// Given
		Type type = typeFactoryForTest.newType();

		TypeEntity typeEntity = typeEntityFactoryForTest.newTypeEntity();
		when(typeJpaRepository.findOne(type.getTypeid())).thenReturn(null);
		
		typeEntity = new TypeEntity();
		typeServiceMapper.mapTypeToTypeEntity(type, typeEntity);
		TypeEntity typeEntitySaved = typeJpaRepository.save(typeEntity);
		
		Type typeSaved = typeFactoryForTest.newType();
		when(typeServiceMapper.mapTypeEntityToType(typeEntitySaved)).thenReturn(typeSaved);

		// When
		Type typeResult = typeService.create(type);

		// Then
		assertTrue(typeResult == typeSaved);
	}

	@Test
	public void createKOExists() {
		// Given
		Type type = typeFactoryForTest.newType();

		TypeEntity typeEntity = typeEntityFactoryForTest.newTypeEntity();
		when(typeJpaRepository.findOne(type.getTypeid())).thenReturn(typeEntity);

		// When
		Exception exception = null;
		try {
			typeService.create(type);
		} catch(Exception e) {
			exception = e;
		}

		// Then
		assertTrue(exception instanceof IllegalStateException);
		assertEquals("already.exists", exception.getMessage());
	}

	@Test
	public void update() {
		// Given
		Type type = typeFactoryForTest.newType();

		TypeEntity typeEntity = typeEntityFactoryForTest.newTypeEntity();
		when(typeJpaRepository.findOne(type.getTypeid())).thenReturn(typeEntity);
		
		TypeEntity typeEntitySaved = typeEntityFactoryForTest.newTypeEntity();
		when(typeJpaRepository.save(typeEntity)).thenReturn(typeEntitySaved);
		
		Type typeSaved = typeFactoryForTest.newType();
		when(typeServiceMapper.mapTypeEntityToType(typeEntitySaved)).thenReturn(typeSaved);

		// When
		Type typeResult = typeService.update(type);

		// Then
		verify(typeServiceMapper).mapTypeToTypeEntity(type, typeEntity);
		assertTrue(typeResult == typeSaved);
	}

	@Test
	public void delete() {
		// Given
		String typeid = mockValues.nextString(255);

		// When
		typeService.delete(typeid);

		// Then
		verify(typeJpaRepository).delete(typeid);
		
	}

}
