/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.web.listitem;

import tristi.general.bean.Returnsupplier;
import tristi.general.web.ListItem;

public class ReturnsupplierListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public ReturnsupplierListItem(Returnsupplier returnsupplier) {
		super();

		this.value = ""
			 + returnsupplier.getReturnsupplierid()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = returnsupplier.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
