/*
 * Created on 6 Dec 2015 ( Time 04:13:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.rest.controller;

import java.util.LinkedList;
import java.util.List;
import java.util.UUID;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import tristi.general.bean.Category;
import tristi.general.business.service.CategoryService;
import tristi.general.web.listitem.CategoryListItem;

/**
 * Spring MVC controller for 'Category' management.
 */
@Controller
public class CategoryRestController {

	@Resource
	private CategoryService categoryService;
	
	@RequestMapping( value="/items/category",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<CategoryListItem> findAllAsListItems() {
		List<Category> list = categoryService.findAll();
		List<CategoryListItem> items = new LinkedList<CategoryListItem>();
		for ( Category category : list ) {
			items.add(new CategoryListItem( category ) );
		}
		return items;
	}
	
	@RequestMapping( value="/category",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Category> findAll() {
		return categoryService.findAll();
	}

	@RequestMapping( value="/category/{categoryid}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Category findOne(@PathVariable("categoryid") String categoryid) {
		return categoryService.findById(categoryid);
	}
	
	@RequestMapping( value="/category",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Category create(@RequestBody Category category) {
            System.out.println(UUID.randomUUID());
		return categoryService.create(category);
	}

	@RequestMapping( value="/category/{categoryid}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Category update(@PathVariable("categoryid") String categoryid, @RequestBody Category category) {
		return categoryService.update(category);
	}

	@RequestMapping( value="/category/{categoryid}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("categoryid") String categoryid) {
		categoryService.delete(categoryid);
	}
	
}
