/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import tristi.general.bean.Pricehistory;
import tristi.general.business.service.PricehistoryService;
import tristi.general.web.listitem.PricehistoryListItem;

/**
 * Spring MVC controller for 'Pricehistory' management.
 */
@Controller
public class PricehistoryRestController {

	@Resource
	private PricehistoryService pricehistoryService;
	
	@RequestMapping( value="/items/pricehistory",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<PricehistoryListItem> findAllAsListItems() {
		List<Pricehistory> list = pricehistoryService.findAll();
		List<PricehistoryListItem> items = new LinkedList<PricehistoryListItem>();
		for ( Pricehistory pricehistory : list ) {
			items.add(new PricehistoryListItem( pricehistory ) );
		}
		return items;
	}
	
	@RequestMapping( value="/pricehistory",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Pricehistory> findAll() {
		return pricehistoryService.findAll();
	}

	@RequestMapping( value="/pricehistory/{pricehistoryid}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Pricehistory findOne(@PathVariable("pricehistoryid") String pricehistoryid) {
		return pricehistoryService.findById(pricehistoryid);
	}
	
	@RequestMapping( value="/pricehistory",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Pricehistory create(@RequestBody Pricehistory pricehistory) {
		return pricehistoryService.create(pricehistory);
	}

	@RequestMapping( value="/pricehistory/{pricehistoryid}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Pricehistory update(@PathVariable("pricehistoryid") String pricehistoryid, @RequestBody Pricehistory pricehistory) {
		return pricehistoryService.update(pricehistory);
	}

	@RequestMapping( value="/pricehistory/{pricehistoryid}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("pricehistoryid") String pricehistoryid) {
		pricehistoryService.delete(pricehistoryid);
	}
	
}
