/*
 * Created on 6 Dec 2015 ( Time 04:09:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.business.service.jpa.mapping;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.modelmapper.ModelMapper;

/**
 * Common mapping methods.
 */
public abstract class AbstractServiceMapper {

	/**
	 * Get ModelMapper.
	 * @return modelMapper
	 */
	protected abstract ModelMapper getModelMapper();
	
	/**
	 * Map input bean to a new output bean.
	 * @param <I> input Input bean
	 * @param <O> outputClass Output bean class
         * @param input
         * @param outputClass
	 * @return New output bean
	 */
	protected <I, O> O map(I input, Class<O> outputClass) {
		return getModelMapper().map(input, outputClass);
	}

	/**
	 * Map input bean to an existing output bean.
	 * @param <I> input Input bean
	 * @param <O> outputClass Output bean class
         * @param input
         * @param output
	 */
	protected <I, O> void map(I input, O output) {
		getModelMapper().map(input, output);
	}
		
	/**
	 * Map input beans to new output beans.
	 * @param <I> input Input bean
	 * @param <O> outputClass Output bean class
         * @param inputs
         * @param outputClass
	 * @return New output beans
	 */
	protected <I, O> List<O> map(Collection<I> inputs, Class<O> outputClass) {
		List<O> outputs = new ArrayList<O>();
		for(I input : inputs) {
			O output = map(input, outputClass);
			outputs.add(output);
		}
		return outputs;
	}

	/**
	 * Map input beans to existing output beans.
	 * @param <I> input Input bean
	 * @param <O> outputClass Output bean class
         * @param inputs
         * @param outputs
         * @param outputClass
	 */
	protected <I, O> void map(Collection<I> inputs, Collection<O> outputs, Class<O> outputClass) {
		for(I input : inputs) {
			O output = map(input, outputClass);
			outputs.add(output);
		}
	}
	
}
