/*
 * Created on 6 Dec 2015 ( Time 04:08:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.business.service.jpa.mapping;

import java.util.UUID;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import tristi.general.bean.Bank;
import tristi.general.bean.jpa.BankEntity;
import tristi.general.bean.jpa.UseraccessEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class BankServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public BankServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'BankEntity' to 'Bank'
	 * @param bankEntity
         * @return Bank
	 */
	public Bank mapBankEntityToBank(BankEntity bankEntity) {
		if(bankEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Bank bank = map(bankEntity, Bank.class);

		//--- Link mapping ( link to Useraccess )
		if(bankEntity.getUseraccess() != null) {
			bank.setBankUserid(bankEntity.getUseraccess().getUserid().toString());
		}
		return bank;
	}
	
	/**
	 * Mapping from 'Bank' to 'BankEntity'
	 * @param bank
	 * @param bankEntity
	 */
	public void mapBankToBankEntity(Bank bank, BankEntity bankEntity) {
		if(bank == null) {
			return;
		}

		//--- Generic mapping 
		map(bank, bankEntity);

		//--- Link mapping ( link : bank )
		if( hasLinkToUseraccess(bank) ) {
			UseraccessEntity useraccess1 = new UseraccessEntity();
			useraccess1.setUserid( UUID.fromString(bank.getBankUserid()));
			bankEntity.setUseraccess( useraccess1 );
		} else {
			bankEntity.setUseraccess( null );
		}

	}
	
	/**
	 * Verify that Useraccess id is valid.
	 * @param Useraccess Useraccess
	 * @return boolean
	 */
	private boolean hasLinkToUseraccess(Bank bank) {
		return bank.getBankUserid() != null;
	}

	/**
	 * {@inheritDoc}
         * @return ModelMapper
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}