/*
 * Created on 6 Dec 2015 ( Time 04:08:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.business.service.jpa.mapping;

import java.util.UUID;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import tristi.general.bean.Category;
import tristi.general.bean.jpa.CategoryEntity;
import tristi.general.bean.jpa.UseraccessEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CategoryServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CategoryServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'CategoryEntity' to 'Category'
	 * @param categoryEntity
         * @return Category
	 */
	public Category mapCategoryEntityToCategory(CategoryEntity categoryEntity) {
		if(categoryEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Category category = map(categoryEntity, Category.class);

		//--- Link mapping ( link to Useraccess )
		if(categoryEntity.getUseraccess() != null) {
			category.setCategoryUserid(categoryEntity.getUseraccess().getUserid().toString());
		}
		return category;
	}
	
	/**
	 * Mapping from 'Category' to 'CategoryEntity'
	 * @param category
	 * @param categoryEntity
	 */
	public void mapCategoryToCategoryEntity(Category category, CategoryEntity categoryEntity) {
		if(category == null) {
			return;
		}

		//--- Generic mapping 
		map(category, categoryEntity);

		//--- Link mapping ( link : category )
		if( hasLinkToUseraccess(category) ) {
			UseraccessEntity useraccess1 = new UseraccessEntity();
			useraccess1.setUserid( UUID.fromString(category.getCategoryUserid()));
			categoryEntity.setUseraccess( useraccess1 );
		} else {
			categoryEntity.setUseraccess( null );
		}

	}
	
	/**
	 * Verify that Useraccess id is valid.
	 * @param Useraccess Useraccess
	 * @return boolean
	 */
	private boolean hasLinkToUseraccess(Category category) {
		return category.getCategoryUserid() != null;
	}

	/**
	 * {@inheritDoc}
         * @return ModelMapper
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}