/*
 * Created on 6 Dec 2015 ( Time 04:08:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.business.service.jpa.mapping;

import java.util.UUID;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import tristi.general.bean.Location;
import tristi.general.bean.jpa.LocationEntity;
import tristi.general.bean.jpa.UseraccessEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class LocationServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public LocationServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'LocationEntity' to 'Location'
	 * @param locationEntity
         * @return Location
	 */
	public Location mapLocationEntityToLocation(LocationEntity locationEntity) {
		if(locationEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Location location = map(locationEntity, Location.class);

		//--- Link mapping ( link to Useraccess )
		if(locationEntity.getUseraccess() != null) {
			location.setLocationUserid(locationEntity.getUseraccess().getUserid().toString());
		}
		return location;
	}
	
	/**
	 * Mapping from 'Location' to 'LocationEntity'
	 * @param location
	 * @param locationEntity
	 */
	public void mapLocationToLocationEntity(Location location, LocationEntity locationEntity) {
		if(location == null) {
			return;
		}

		//--- Generic mapping 
		map(location, locationEntity);

		//--- Link mapping ( link : location )
		if( hasLinkToUseraccess(location) ) {
			UseraccessEntity useraccess1 = new UseraccessEntity();
			useraccess1.setUserid( UUID.fromString(location.getLocationUserid()));
			locationEntity.setUseraccess( useraccess1 );
		} else {
			locationEntity.setUseraccess( null );
		}

	}
	
	/**
	 * Verify that Useraccess id is valid.
	 * @param Useraccess Useraccess
	 * @return boolean
	 */
	private boolean hasLinkToUseraccess(Location location) {
		return location.getLocationUserid() != null;
	}

	/**
	 * {@inheritDoc}
         * @return ModelMapper
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}