/*
 * Created on 6 Dec 2015 ( Time 04:08:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.business.service.jpa.mapping;

import java.util.UUID;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import tristi.general.bean.Supplier;
import tristi.general.bean.jpa.SupplierEntity;
import tristi.general.bean.jpa.UseraccessEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class SupplierServiceMapper extends AbstractServiceMapper {

    /**
     * ModelMapper : bean to bean mapping library.
     */
    private ModelMapper modelMapper;

    /**
     * Constructor.
     */
    public SupplierServiceMapper() {
        modelMapper = new ModelMapper();
        modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
    }

    /**
     * Mapping from 'SupplierEntity' to 'Supplier'
     *
     * @param supplierEntity
     * @return Supplier
     */
    public Supplier mapSupplierEntityToSupplier(SupplierEntity supplierEntity) {
        if (supplierEntity == null) {
            return null;
        }

        //--- Generic mapping 
        Supplier supplier = map(supplierEntity, Supplier.class);

        //--- Link mapping ( link to Useraccess )
        if (supplierEntity.getUseraccess() != null) {
            supplier.setSupplierUserid(supplierEntity.getUseraccess().getUserid().toString());
        }
        return supplier;
    }

    /**
     * Mapping from 'Supplier' to 'SupplierEntity'
     *
     * @param supplier
     * @param supplierEntity
     */
    public void mapSupplierToSupplierEntity(Supplier supplier, SupplierEntity supplierEntity) {
        if (supplier == null) {
            return;
        }

        //--- Generic mapping 
        map(supplier, supplierEntity);

        //--- Link mapping ( link : supplier )
        if (hasLinkToUseraccess(supplier)) {
            UseraccessEntity useraccess1 = new UseraccessEntity();
            useraccess1.setUserid(UUID.fromString(supplier.getSupplierUserid()));
            supplierEntity.setUseraccess(useraccess1);
        } else {
            supplierEntity.setUseraccess(null);
        }

    }

    /**
     * Verify that Useraccess id is valid.
     *
     * @param Useraccess Useraccess
     * @return boolean
     */
    private boolean hasLinkToUseraccess(Supplier supplier) {
        return supplier.getSupplierUserid() != null;
    }

    /**
     * {@inheritDoc}
     *
     * @return ModelMapper
     */
    @Override
    protected ModelMapper getModelMapper() {
        return modelMapper;
    }

    protected void setModelMapper(ModelMapper modelMapper) {
        this.modelMapper = modelMapper;
    }

}
