/*
 * Created on 6 Dec 2015 ( Time 04:13:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Accountbank implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String accountbankid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String accountbankSupplierid;

    @Size( max = 255 )
    private String accountbankSalesorderid;

    @Size( max = 255 )
    private String accountbankBankid;

    @Size( max = 255 )
    private String accountbankUserid;

    @Size( max = 50 )
    private String accountbanknumber;

    @Size( max = 100 )
    private String accountbankname;


    private Boolean accountbankissales;


    private Date accountbankmoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setAccountbankid( String accountbankid ) {
        this.accountbankid = accountbankid ;
    }

    public String getAccountbankid() {
        return this.accountbankid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setAccountbankSupplierid( String accountbankSupplierid ) {
        this.accountbankSupplierid = accountbankSupplierid;
    }
    public String getAccountbankSupplierid() {
        return this.accountbankSupplierid;
    }

    public void setAccountbankSalesorderid( String accountbankSalesorderid ) {
        this.accountbankSalesorderid = accountbankSalesorderid;
    }
    public String getAccountbankSalesorderid() {
        return this.accountbankSalesorderid;
    }

    public void setAccountbankBankid( String accountbankBankid ) {
        this.accountbankBankid = accountbankBankid;
    }
    public String getAccountbankBankid() {
        return this.accountbankBankid;
    }

    public void setAccountbankUserid( String accountbankUserid ) {
        this.accountbankUserid = accountbankUserid;
    }
    public String getAccountbankUserid() {
        return this.accountbankUserid;
    }

    public void setAccountbanknumber( String accountbanknumber ) {
        this.accountbanknumber = accountbanknumber;
    }
    public String getAccountbanknumber() {
        return this.accountbanknumber;
    }

    public void setAccountbankname( String accountbankname ) {
        this.accountbankname = accountbankname;
    }
    public String getAccountbankname() {
        return this.accountbankname;
    }

    public void setAccountbankissales( Boolean accountbankissales ) {
        this.accountbankissales = accountbankissales;
    }
    public Boolean getAccountbankissales() {
        return this.accountbankissales;
    }

    public void setAccountbankmoddate( Date accountbankmoddate ) {
        this.accountbankmoddate = accountbankmoddate;
    }
    public Date getAccountbankmoddate() {
        return this.accountbankmoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(accountbankid);
        sb.append("|");
        sb.append(accountbankSupplierid);
        sb.append("|");
        sb.append(accountbankSalesorderid);
        sb.append("|");
        sb.append(accountbankBankid);
        sb.append("|");
        sb.append(accountbankUserid);
        sb.append("|");
        sb.append(accountbanknumber);
        sb.append("|");
        sb.append(accountbankname);
        sb.append("|");
        sb.append(accountbankissales);
        sb.append("|");
        sb.append(accountbankmoddate);
        return sb.toString(); 
    } 


}
