/*
 * Created on 6 Dec 2015 ( Time 04:13:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Bank implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String bankid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String bankUserid;

    @Size( max = 50 )
    private String bankname;

    @Size( max = 100 )
    private String bankdescription;


    private Boolean bankisactive;


    private Date bankmoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setBankid( String bankid ) {
        this.bankid = bankid ;
    }

    public String getBankid() {
        return this.bankid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setBankUserid( String bankUserid ) {
        this.bankUserid = bankUserid;
    }
    public String getBankUserid() {
        return this.bankUserid;
    }

    public void setBankname( String bankname ) {
        this.bankname = bankname;
    }
    public String getBankname() {
        return this.bankname;
    }

    public void setBankdescription( String bankdescription ) {
        this.bankdescription = bankdescription;
    }
    public String getBankdescription() {
        return this.bankdescription;
    }

    public void setBankisactive( Boolean bankisactive ) {
        this.bankisactive = bankisactive;
    }
    public Boolean getBankisactive() {
        return this.bankisactive;
    }

    public void setBankmoddate( Date bankmoddate ) {
        this.bankmoddate = bankmoddate;
    }
    public Date getBankmoddate() {
        return this.bankmoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(bankid);
        sb.append("|");
        sb.append(bankUserid);
        sb.append("|");
        sb.append(bankname);
        sb.append("|");
        sb.append(bankdescription);
        sb.append("|");
        sb.append(bankisactive);
        sb.append("|");
        sb.append(bankmoddate);
        return sb.toString(); 
    } 


}
