/*
 * Created on 6 Dec 2015 ( Time 04:13:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Category implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String categoryid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String categoryUserid;

    @NotNull
    @Size( max = 50 )
    private String categorycode;

    @Size( max = 100 )
    private String categoryname;


    private Boolean categoryisactive;


    private Date categorymoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCategoryid( String categoryid ) {
        this.categoryid = categoryid ;
    }

    public String getCategoryid() {
        return this.categoryid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCategoryUserid( String categoryUserid ) {
        this.categoryUserid = categoryUserid;
    }
    public String getCategoryUserid() {
        return this.categoryUserid;
    }

    public void setCategorycode( String categorycode ) {
        this.categorycode = categorycode;
    }
    public String getCategorycode() {
        return this.categorycode;
    }

    public void setCategoryname( String categoryname ) {
        this.categoryname = categoryname;
    }
    public String getCategoryname() {
        return this.categoryname;
    }

    public void setCategoryisactive( Boolean categoryisactive ) {
        this.categoryisactive = categoryisactive;
    }
    public Boolean getCategoryisactive() {
        return this.categoryisactive;
    }

    public void setCategorymoddate( Date categorymoddate ) {
        this.categorymoddate = categorymoddate;
    }
    public Date getCategorymoddate() {
        return this.categorymoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(categoryid);
        sb.append("|");
        sb.append(categoryUserid);
        sb.append("|");
        sb.append(categorycode);
        sb.append("|");
        sb.append(categoryname);
        sb.append("|");
        sb.append(categoryisactive);
        sb.append("|");
        sb.append(categorymoddate);
        return sb.toString(); 
    } 


}
