/*
 * Created on 6 Dec 2015 ( Time 04:13:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Detailexpired implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String detailexpiredid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String detailexpiredProductstockid;

    @Size( max = 255 )
    private String detailexpiredUserid;

    @Size( max = 255 )
    private String detailexpiredLocationdtlid;


    private Date detailexpireddate;


    private Integer detailexpiredqty;


    private Date detailexpiredmoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setDetailexpiredid( String detailexpiredid ) {
        this.detailexpiredid = detailexpiredid ;
    }

    public String getDetailexpiredid() {
        return this.detailexpiredid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDetailexpiredProductstockid( String detailexpiredProductstockid ) {
        this.detailexpiredProductstockid = detailexpiredProductstockid;
    }
    public String getDetailexpiredProductstockid() {
        return this.detailexpiredProductstockid;
    }

    public void setDetailexpiredUserid( String detailexpiredUserid ) {
        this.detailexpiredUserid = detailexpiredUserid;
    }
    public String getDetailexpiredUserid() {
        return this.detailexpiredUserid;
    }

    public void setDetailexpiredLocationdtlid( String detailexpiredLocationdtlid ) {
        this.detailexpiredLocationdtlid = detailexpiredLocationdtlid;
    }
    public String getDetailexpiredLocationdtlid() {
        return this.detailexpiredLocationdtlid;
    }

    public void setDetailexpireddate( Date detailexpireddate ) {
        this.detailexpireddate = detailexpireddate;
    }
    public Date getDetailexpireddate() {
        return this.detailexpireddate;
    }

    public void setDetailexpiredqty( Integer detailexpiredqty ) {
        this.detailexpiredqty = detailexpiredqty;
    }
    public Integer getDetailexpiredqty() {
        return this.detailexpiredqty;
    }

    public void setDetailexpiredmoddate( Date detailexpiredmoddate ) {
        this.detailexpiredmoddate = detailexpiredmoddate;
    }
    public Date getDetailexpiredmoddate() {
        return this.detailexpiredmoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(detailexpiredid);
        sb.append("|");
        sb.append(detailexpiredProductstockid);
        sb.append("|");
        sb.append(detailexpiredUserid);
        sb.append("|");
        sb.append(detailexpiredLocationdtlid);
        sb.append("|");
        sb.append(detailexpireddate);
        sb.append("|");
        sb.append(detailexpiredqty);
        sb.append("|");
        sb.append(detailexpiredmoddate);
        return sb.toString(); 
    } 


}
