/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Location implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String locationid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String locationUserid;

    @Size( max = 100 )
    private String locationcode;

    @Size( max = 100 )
    private String locationname;


    private Boolean locationismain;


    private Boolean locationisactive;


    private Date locationmoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setLocationid( String locationid ) {
        this.locationid = locationid ;
    }

    public String getLocationid() {
        return this.locationid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setLocationUserid( String locationUserid ) {
        this.locationUserid = locationUserid;
    }
    public String getLocationUserid() {
        return this.locationUserid;
    }

    public void setLocationcode( String locationcode ) {
        this.locationcode = locationcode;
    }
    public String getLocationcode() {
        return this.locationcode;
    }

    public void setLocationname( String locationname ) {
        this.locationname = locationname;
    }
    public String getLocationname() {
        return this.locationname;
    }

    public void setLocationismain( Boolean locationismain ) {
        this.locationismain = locationismain;
    }
    public Boolean getLocationismain() {
        return this.locationismain;
    }

    public void setLocationisactive( Boolean locationisactive ) {
        this.locationisactive = locationisactive;
    }
    public Boolean getLocationisactive() {
        return this.locationisactive;
    }

    public void setLocationmoddate( Date locationmoddate ) {
        this.locationmoddate = locationmoddate;
    }
    public Date getLocationmoddate() {
        return this.locationmoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(locationid);
        sb.append("|");
        sb.append(locationUserid);
        sb.append("|");
        sb.append(locationcode);
        sb.append("|");
        sb.append(locationname);
        sb.append("|");
        sb.append(locationismain);
        sb.append("|");
        sb.append(locationisactive);
        sb.append("|");
        sb.append(locationmoddate);
        return sb.toString(); 
    } 


}
