/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Paymentform implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String paymentformid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String paymentformUserid;

    @Size( max = 50 )
    private String paymentformcode;

    @Size( max = 50 )
    private String paymentformname;


    private Boolean paymentformiscredit;


    private Boolean paymentformneedbank;


    private Boolean paymentformisactive;


    private Date paymentformmoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPaymentformid( String paymentformid ) {
        this.paymentformid = paymentformid ;
    }

    public String getPaymentformid() {
        return this.paymentformid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPaymentformUserid( String paymentformUserid ) {
        this.paymentformUserid = paymentformUserid;
    }
    public String getPaymentformUserid() {
        return this.paymentformUserid;
    }

    public void setPaymentformcode( String paymentformcode ) {
        this.paymentformcode = paymentformcode;
    }
    public String getPaymentformcode() {
        return this.paymentformcode;
    }

    public void setPaymentformname( String paymentformname ) {
        this.paymentformname = paymentformname;
    }
    public String getPaymentformname() {
        return this.paymentformname;
    }

    public void setPaymentformiscredit( Boolean paymentformiscredit ) {
        this.paymentformiscredit = paymentformiscredit;
    }
    public Boolean getPaymentformiscredit() {
        return this.paymentformiscredit;
    }

    public void setPaymentformneedbank( Boolean paymentformneedbank ) {
        this.paymentformneedbank = paymentformneedbank;
    }
    public Boolean getPaymentformneedbank() {
        return this.paymentformneedbank;
    }

    public void setPaymentformisactive( Boolean paymentformisactive ) {
        this.paymentformisactive = paymentformisactive;
    }
    public Boolean getPaymentformisactive() {
        return this.paymentformisactive;
    }

    public void setPaymentformmoddate( Date paymentformmoddate ) {
        this.paymentformmoddate = paymentformmoddate;
    }
    public Date getPaymentformmoddate() {
        return this.paymentformmoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(paymentformid);
        sb.append("|");
        sb.append(paymentformUserid);
        sb.append("|");
        sb.append(paymentformcode);
        sb.append("|");
        sb.append(paymentformname);
        sb.append("|");
        sb.append(paymentformiscredit);
        sb.append("|");
        sb.append(paymentformneedbank);
        sb.append("|");
        sb.append(paymentformisactive);
        sb.append("|");
        sb.append(paymentformmoddate);
        return sb.toString(); 
    } 


}
