/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Product implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String productid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String productUserid;

    @Size( max = 255 )
    private String productTypeid;

    @Size( max = 255 )
    private String productCategoryid;

    @Size( max = 50 )
    private String productcode;

    @Size( max = 100 )
    private String productname;


    private Boolean productisactive;


    private Double productbaseprice;


    private Double productprice;


    private Date productmoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setProductid( String productid ) {
        this.productid = productid ;
    }

    public String getProductid() {
        return this.productid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setProductUserid( String productUserid ) {
        this.productUserid = productUserid;
    }
    public String getProductUserid() {
        return this.productUserid;
    }

    public void setProductTypeid( String productTypeid ) {
        this.productTypeid = productTypeid;
    }
    public String getProductTypeid() {
        return this.productTypeid;
    }

    public void setProductCategoryid( String productCategoryid ) {
        this.productCategoryid = productCategoryid;
    }
    public String getProductCategoryid() {
        return this.productCategoryid;
    }

    public void setProductcode( String productcode ) {
        this.productcode = productcode;
    }
    public String getProductcode() {
        return this.productcode;
    }

    public void setProductname( String productname ) {
        this.productname = productname;
    }
    public String getProductname() {
        return this.productname;
    }

    public void setProductisactive( Boolean productisactive ) {
        this.productisactive = productisactive;
    }
    public Boolean getProductisactive() {
        return this.productisactive;
    }

    public void setProductbaseprice( Double productbaseprice ) {
        this.productbaseprice = productbaseprice;
    }
    public Double getProductbaseprice() {
        return this.productbaseprice;
    }

    public void setProductprice( Double productprice ) {
        this.productprice = productprice;
    }
    public Double getProductprice() {
        return this.productprice;
    }

    public void setProductmoddate( Date productmoddate ) {
        this.productmoddate = productmoddate;
    }
    public Date getProductmoddate() {
        return this.productmoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(productid);
        sb.append("|");
        sb.append(productUserid);
        sb.append("|");
        sb.append(productTypeid);
        sb.append("|");
        sb.append(productCategoryid);
        sb.append("|");
        sb.append(productcode);
        sb.append("|");
        sb.append(productname);
        sb.append("|");
        sb.append(productisactive);
        sb.append("|");
        sb.append(productbaseprice);
        sb.append("|");
        sb.append(productprice);
        sb.append("|");
        sb.append(productmoddate);
        return sb.toString(); 
    } 


}
