/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Purchaseorderdtl implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String purchaseorderdtlid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String podtlPoid;

    @Size( max = 255 )
    private String podtlProductuomid;

    @Size( max = 255 )
    private String podtlUserid;

    @Size( max = 255 )
    private String podtlDetailexpiredid;


    private Integer purchaseorderdtlqty;


    private Integer purchaseorderdtlremainingqty;


    private Double purchaseorderdtlprice;


    private Double purchaseorderdtldiscount;


    private Date purchaseorderdtlmoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPurchaseorderdtlid( String purchaseorderdtlid ) {
        this.purchaseorderdtlid = purchaseorderdtlid ;
    }

    public String getPurchaseorderdtlid() {
        return this.purchaseorderdtlid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPodtlPoid( String podtlPoid ) {
        this.podtlPoid = podtlPoid;
    }
    public String getPodtlPoid() {
        return this.podtlPoid;
    }

    public void setPodtlProductuomid( String podtlProductuomid ) {
        this.podtlProductuomid = podtlProductuomid;
    }
    public String getPodtlProductuomid() {
        return this.podtlProductuomid;
    }

    public void setPodtlUserid( String podtlUserid ) {
        this.podtlUserid = podtlUserid;
    }
    public String getPodtlUserid() {
        return this.podtlUserid;
    }

    public void setPodtlDetailexpiredid( String podtlDetailexpiredid ) {
        this.podtlDetailexpiredid = podtlDetailexpiredid;
    }
    public String getPodtlDetailexpiredid() {
        return this.podtlDetailexpiredid;
    }

    public void setPurchaseorderdtlqty( Integer purchaseorderdtlqty ) {
        this.purchaseorderdtlqty = purchaseorderdtlqty;
    }
    public Integer getPurchaseorderdtlqty() {
        return this.purchaseorderdtlqty;
    }

    public void setPurchaseorderdtlremainingqty( Integer purchaseorderdtlremainingqty ) {
        this.purchaseorderdtlremainingqty = purchaseorderdtlremainingqty;
    }
    public Integer getPurchaseorderdtlremainingqty() {
        return this.purchaseorderdtlremainingqty;
    }

    public void setPurchaseorderdtlprice( Double purchaseorderdtlprice ) {
        this.purchaseorderdtlprice = purchaseorderdtlprice;
    }
    public Double getPurchaseorderdtlprice() {
        return this.purchaseorderdtlprice;
    }

    public void setPurchaseorderdtldiscount( Double purchaseorderdtldiscount ) {
        this.purchaseorderdtldiscount = purchaseorderdtldiscount;
    }
    public Double getPurchaseorderdtldiscount() {
        return this.purchaseorderdtldiscount;
    }

    public void setPurchaseorderdtlmoddate( Date purchaseorderdtlmoddate ) {
        this.purchaseorderdtlmoddate = purchaseorderdtlmoddate;
    }
    public Date getPurchaseorderdtlmoddate() {
        return this.purchaseorderdtlmoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(purchaseorderdtlid);
        sb.append("|");
        sb.append(podtlPoid);
        sb.append("|");
        sb.append(podtlProductuomid);
        sb.append("|");
        sb.append(podtlUserid);
        sb.append("|");
        sb.append(podtlDetailexpiredid);
        sb.append("|");
        sb.append(purchaseorderdtlqty);
        sb.append("|");
        sb.append(purchaseorderdtlremainingqty);
        sb.append("|");
        sb.append(purchaseorderdtlprice);
        sb.append("|");
        sb.append(purchaseorderdtldiscount);
        sb.append("|");
        sb.append(purchaseorderdtlmoddate);
        return sb.toString(); 
    } 


}
