/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Returnsupplier implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String returnsupplierid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String returnsupplierUserid;

    @Size( max = 255 )
    private String returnsupplierSupplierid;

    @Size( max = 50 )
    private String returnsuppliercode;


    private Date returnsupplierdate;


    private Double returnsupplieramount;

    @Size( max = 50 )
    private String returnsupplierstatus;


    private Date returnsuppliermoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setReturnsupplierid( String returnsupplierid ) {
        this.returnsupplierid = returnsupplierid ;
    }

    public String getReturnsupplierid() {
        return this.returnsupplierid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setReturnsupplierUserid( String returnsupplierUserid ) {
        this.returnsupplierUserid = returnsupplierUserid;
    }
    public String getReturnsupplierUserid() {
        return this.returnsupplierUserid;
    }

    public void setReturnsupplierSupplierid( String returnsupplierSupplierid ) {
        this.returnsupplierSupplierid = returnsupplierSupplierid;
    }
    public String getReturnsupplierSupplierid() {
        return this.returnsupplierSupplierid;
    }

    public void setReturnsuppliercode( String returnsuppliercode ) {
        this.returnsuppliercode = returnsuppliercode;
    }
    public String getReturnsuppliercode() {
        return this.returnsuppliercode;
    }

    public void setReturnsupplierdate( Date returnsupplierdate ) {
        this.returnsupplierdate = returnsupplierdate;
    }
    public Date getReturnsupplierdate() {
        return this.returnsupplierdate;
    }

    public void setReturnsupplieramount( Double returnsupplieramount ) {
        this.returnsupplieramount = returnsupplieramount;
    }
    public Double getReturnsupplieramount() {
        return this.returnsupplieramount;
    }

    public void setReturnsupplierstatus( String returnsupplierstatus ) {
        this.returnsupplierstatus = returnsupplierstatus;
    }
    public String getReturnsupplierstatus() {
        return this.returnsupplierstatus;
    }

    public void setReturnsuppliermoddate( Date returnsuppliermoddate ) {
        this.returnsuppliermoddate = returnsuppliermoddate;
    }
    public Date getReturnsuppliermoddate() {
        return this.returnsuppliermoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(returnsupplierid);
        sb.append("|");
        sb.append(returnsupplierUserid);
        sb.append("|");
        sb.append(returnsupplierSupplierid);
        sb.append("|");
        sb.append(returnsuppliercode);
        sb.append("|");
        sb.append(returnsupplierdate);
        sb.append("|");
        sb.append(returnsupplieramount);
        sb.append("|");
        sb.append(returnsupplierstatus);
        sb.append("|");
        sb.append(returnsuppliermoddate);
        return sb.toString(); 
    } 


}
