/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Returnsupplierdtl implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String returndtlid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String returndtlReturnsupplierid;

    @Size( max = 255 )
    private String returndtlProductuomid;

    @Size( max = 255 )
    private String returndtlUserid;

    @Size( max = 255 )
    private String returndtlDetailexpiredid;


    private Integer returndtlqty;


    private Double returndtlprice;


    private Date returnrdtlmoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setReturndtlid( String returndtlid ) {
        this.returndtlid = returndtlid ;
    }

    public String getReturndtlid() {
        return this.returndtlid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setReturndtlReturnsupplierid( String returndtlReturnsupplierid ) {
        this.returndtlReturnsupplierid = returndtlReturnsupplierid;
    }
    public String getReturndtlReturnsupplierid() {
        return this.returndtlReturnsupplierid;
    }

    public void setReturndtlProductuomid( String returndtlProductuomid ) {
        this.returndtlProductuomid = returndtlProductuomid;
    }
    public String getReturndtlProductuomid() {
        return this.returndtlProductuomid;
    }

    public void setReturndtlUserid( String returndtlUserid ) {
        this.returndtlUserid = returndtlUserid;
    }
    public String getReturndtlUserid() {
        return this.returndtlUserid;
    }

    public void setReturndtlDetailexpiredid( String returndtlDetailexpiredid ) {
        this.returndtlDetailexpiredid = returndtlDetailexpiredid;
    }
    public String getReturndtlDetailexpiredid() {
        return this.returndtlDetailexpiredid;
    }

    public void setReturndtlqty( Integer returndtlqty ) {
        this.returndtlqty = returndtlqty;
    }
    public Integer getReturndtlqty() {
        return this.returndtlqty;
    }

    public void setReturndtlprice( Double returndtlprice ) {
        this.returndtlprice = returndtlprice;
    }
    public Double getReturndtlprice() {
        return this.returndtlprice;
    }

    public void setReturnrdtlmoddate( Date returnrdtlmoddate ) {
        this.returnrdtlmoddate = returnrdtlmoddate;
    }
    public Date getReturnrdtlmoddate() {
        return this.returnrdtlmoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(returndtlid);
        sb.append("|");
        sb.append(returndtlReturnsupplierid);
        sb.append("|");
        sb.append(returndtlProductuomid);
        sb.append("|");
        sb.append(returndtlUserid);
        sb.append("|");
        sb.append(returndtlDetailexpiredid);
        sb.append("|");
        sb.append(returndtlqty);
        sb.append("|");
        sb.append(returndtlprice);
        sb.append("|");
        sb.append(returnrdtlmoddate);
        return sb.toString(); 
    } 


}
