/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Salesordercorrection implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String salesordercorrectionid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String salesordercorrectionSodtlid;

    @Size( max = 255 )
    private String salesordercorrectionUserid;


    private Integer salesordercorrectionqty;


    private Double salesordercorrectionprice;


    private Double salesordercorrectionbaseprice;


    private Double salesordercorrectiondiscount;


    private Date salesordercorrectionmoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSalesordercorrectionid( String salesordercorrectionid ) {
        this.salesordercorrectionid = salesordercorrectionid ;
    }

    public String getSalesordercorrectionid() {
        return this.salesordercorrectionid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setSalesordercorrectionSodtlid( String salesordercorrectionSodtlid ) {
        this.salesordercorrectionSodtlid = salesordercorrectionSodtlid;
    }
    public String getSalesordercorrectionSodtlid() {
        return this.salesordercorrectionSodtlid;
    }

    public void setSalesordercorrectionUserid( String salesordercorrectionUserid ) {
        this.salesordercorrectionUserid = salesordercorrectionUserid;
    }
    public String getSalesordercorrectionUserid() {
        return this.salesordercorrectionUserid;
    }

    public void setSalesordercorrectionqty( Integer salesordercorrectionqty ) {
        this.salesordercorrectionqty = salesordercorrectionqty;
    }
    public Integer getSalesordercorrectionqty() {
        return this.salesordercorrectionqty;
    }

    public void setSalesordercorrectionprice( Double salesordercorrectionprice ) {
        this.salesordercorrectionprice = salesordercorrectionprice;
    }
    public Double getSalesordercorrectionprice() {
        return this.salesordercorrectionprice;
    }

    public void setSalesordercorrectionbaseprice( Double salesordercorrectionbaseprice ) {
        this.salesordercorrectionbaseprice = salesordercorrectionbaseprice;
    }
    public Double getSalesordercorrectionbaseprice() {
        return this.salesordercorrectionbaseprice;
    }

    public void setSalesordercorrectiondiscount( Double salesordercorrectiondiscount ) {
        this.salesordercorrectiondiscount = salesordercorrectiondiscount;
    }
    public Double getSalesordercorrectiondiscount() {
        return this.salesordercorrectiondiscount;
    }

    public void setSalesordercorrectionmoddate( Date salesordercorrectionmoddate ) {
        this.salesordercorrectionmoddate = salesordercorrectionmoddate;
    }
    public Date getSalesordercorrectionmoddate() {
        return this.salesordercorrectionmoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(salesordercorrectionid);
        sb.append("|");
        sb.append(salesordercorrectionSodtlid);
        sb.append("|");
        sb.append(salesordercorrectionUserid);
        sb.append("|");
        sb.append(salesordercorrectionqty);
        sb.append("|");
        sb.append(salesordercorrectionprice);
        sb.append("|");
        sb.append(salesordercorrectionbaseprice);
        sb.append("|");
        sb.append(salesordercorrectiondiscount);
        sb.append("|");
        sb.append(salesordercorrectionmoddate);
        return sb.toString(); 
    } 


}
