/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Salesorder implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String salesorderid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String paymentformid;

    @Size( max = 255 )
    private String salesordercorrectionId;

    @Size( max = 255 )
    private String salesorderUserid;

    @Size( max = 50 )
    private String salesordercode;


    private Date salesorderdate;


    private Date salesorderdeliverydate;

    @Size( max = 50 )
    private String salesorderstatus;


    private Double salesorderdiscount;


    private Double salesorderbilling;


    private Double salesorderpaying;


    private Boolean salesorderincludetax;


    private Date salesordermoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSalesorderid( String salesorderid ) {
        this.salesorderid = salesorderid ;
    }

    public String getSalesorderid() {
        return this.salesorderid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setPaymentformid( String paymentformid ) {
        this.paymentformid = paymentformid;
    }
    public String getPaymentformid() {
        return this.paymentformid;
    }

    public void setSalesordercorrectionId( String salesordercorrectionId ) {
        this.salesordercorrectionId = salesordercorrectionId;
    }
    public String getSalesordercorrectionId() {
        return this.salesordercorrectionId;
    }

    public void setSalesorderUserid( String salesorderUserid ) {
        this.salesorderUserid = salesorderUserid;
    }
    public String getSalesorderUserid() {
        return this.salesorderUserid;
    }

    public void setSalesordercode( String salesordercode ) {
        this.salesordercode = salesordercode;
    }
    public String getSalesordercode() {
        return this.salesordercode;
    }

    public void setSalesorderdate( Date salesorderdate ) {
        this.salesorderdate = salesorderdate;
    }
    public Date getSalesorderdate() {
        return this.salesorderdate;
    }

    public void setSalesorderdeliverydate( Date salesorderdeliverydate ) {
        this.salesorderdeliverydate = salesorderdeliverydate;
    }
    public Date getSalesorderdeliverydate() {
        return this.salesorderdeliverydate;
    }

    public void setSalesorderstatus( String salesorderstatus ) {
        this.salesorderstatus = salesorderstatus;
    }
    public String getSalesorderstatus() {
        return this.salesorderstatus;
    }

    public void setSalesorderdiscount( Double salesorderdiscount ) {
        this.salesorderdiscount = salesorderdiscount;
    }
    public Double getSalesorderdiscount() {
        return this.salesorderdiscount;
    }

    public void setSalesorderbilling( Double salesorderbilling ) {
        this.salesorderbilling = salesorderbilling;
    }
    public Double getSalesorderbilling() {
        return this.salesorderbilling;
    }

    public void setSalesorderpaying( Double salesorderpaying ) {
        this.salesorderpaying = salesorderpaying;
    }
    public Double getSalesorderpaying() {
        return this.salesorderpaying;
    }

    public void setSalesorderincludetax( Boolean salesorderincludetax ) {
        this.salesorderincludetax = salesorderincludetax;
    }
    public Boolean getSalesorderincludetax() {
        return this.salesorderincludetax;
    }

    public void setSalesordermoddate( Date salesordermoddate ) {
        this.salesordermoddate = salesordermoddate;
    }
    public Date getSalesordermoddate() {
        return this.salesordermoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(salesorderid);
        sb.append("|");
        sb.append(paymentformid);
        sb.append("|");
        sb.append(salesordercorrectionId);
        sb.append("|");
        sb.append(salesorderUserid);
        sb.append("|");
        sb.append(salesordercode);
        sb.append("|");
        sb.append(salesorderdate);
        sb.append("|");
        sb.append(salesorderdeliverydate);
        sb.append("|");
        sb.append(salesorderstatus);
        sb.append("|");
        sb.append(salesorderdiscount);
        sb.append("|");
        sb.append(salesorderbilling);
        sb.append("|");
        sb.append(salesorderpaying);
        sb.append("|");
        sb.append(salesorderincludetax);
        sb.append("|");
        sb.append(salesordermoddate);
        return sb.toString(); 
    } 


}
