/*
 * Created on 6 Dec 2015 ( Time 04:13:34 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Supplier implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String supplierid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String supplierUserid;

    @Size( max = 50 )
    private String suppliercode;

    @Size( max = 100 )
    private String suppliername;

    @Size( max = 200 )
    private String supplieraddres;

    @Size( max = 50 )
    private String suppliercity;

    @Size( max = 20 )
    private String supplierphone1;

    @Size( max = 20 )
    private String supplierphone2;

    @Size( max = 20 )
    private String supplierfax1;

    @Size( max = 20 )
    private String supplierfax2;


    private Boolean supplierisactive;


    private Date suppliermoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSupplierid( String supplierid ) {
        this.supplierid = supplierid ;
    }

    public String getSupplierid() {
        return this.supplierid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setSupplierUserid( String supplierUserid ) {
        this.supplierUserid = supplierUserid;
    }
    public String getSupplierUserid() {
        return this.supplierUserid;
    }

    public void setSuppliercode( String suppliercode ) {
        this.suppliercode = suppliercode;
    }
    public String getSuppliercode() {
        return this.suppliercode;
    }

    public void setSuppliername( String suppliername ) {
        this.suppliername = suppliername;
    }
    public String getSuppliername() {
        return this.suppliername;
    }

    public void setSupplieraddres( String supplieraddres ) {
        this.supplieraddres = supplieraddres;
    }
    public String getSupplieraddres() {
        return this.supplieraddres;
    }

    public void setSuppliercity( String suppliercity ) {
        this.suppliercity = suppliercity;
    }
    public String getSuppliercity() {
        return this.suppliercity;
    }

    public void setSupplierphone1( String supplierphone1 ) {
        this.supplierphone1 = supplierphone1;
    }
    public String getSupplierphone1() {
        return this.supplierphone1;
    }

    public void setSupplierphone2( String supplierphone2 ) {
        this.supplierphone2 = supplierphone2;
    }
    public String getSupplierphone2() {
        return this.supplierphone2;
    }

    public void setSupplierfax1( String supplierfax1 ) {
        this.supplierfax1 = supplierfax1;
    }
    public String getSupplierfax1() {
        return this.supplierfax1;
    }

    public void setSupplierfax2( String supplierfax2 ) {
        this.supplierfax2 = supplierfax2;
    }
    public String getSupplierfax2() {
        return this.supplierfax2;
    }

    public void setSupplierisactive( Boolean supplierisactive ) {
        this.supplierisactive = supplierisactive;
    }
    public Boolean getSupplierisactive() {
        return this.supplierisactive;
    }

    public void setSuppliermoddate( Date suppliermoddate ) {
        this.suppliermoddate = suppliermoddate;
    }
    public Date getSuppliermoddate() {
        return this.suppliermoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(supplierid);
        sb.append("|");
        sb.append(supplierUserid);
        sb.append("|");
        sb.append(suppliercode);
        sb.append("|");
        sb.append(suppliername);
        sb.append("|");
        sb.append(supplieraddres);
        sb.append("|");
        sb.append(suppliercity);
        sb.append("|");
        sb.append(supplierphone1);
        sb.append("|");
        sb.append(supplierphone2);
        sb.append("|");
        sb.append(supplierfax1);
        sb.append("|");
        sb.append(supplierfax2);
        sb.append("|");
        sb.append(supplierisactive);
        sb.append("|");
        sb.append(suppliermoddate);
        return sb.toString(); 
    } 


}
