/*
 * Created on 6 Dec 2015 ( Time 04:13:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Supplierproduct implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String supplierproductid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String supplierproductProductid;

    @Size( max = 255 )
    private String supplierproductUserid;

    @Size( max = 255 )
    private String supplierproductSupplierid;


    private Boolean supplierproductisactive;


    private Date supplierproductmoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setSupplierproductid( String supplierproductid ) {
        this.supplierproductid = supplierproductid ;
    }

    public String getSupplierproductid() {
        return this.supplierproductid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setSupplierproductProductid( String supplierproductProductid ) {
        this.supplierproductProductid = supplierproductProductid;
    }
    public String getSupplierproductProductid() {
        return this.supplierproductProductid;
    }

    public void setSupplierproductUserid( String supplierproductUserid ) {
        this.supplierproductUserid = supplierproductUserid;
    }
    public String getSupplierproductUserid() {
        return this.supplierproductUserid;
    }

    public void setSupplierproductSupplierid( String supplierproductSupplierid ) {
        this.supplierproductSupplierid = supplierproductSupplierid;
    }
    public String getSupplierproductSupplierid() {
        return this.supplierproductSupplierid;
    }

    public void setSupplierproductisactive( Boolean supplierproductisactive ) {
        this.supplierproductisactive = supplierproductisactive;
    }
    public Boolean getSupplierproductisactive() {
        return this.supplierproductisactive;
    }

    public void setSupplierproductmoddate( Date supplierproductmoddate ) {
        this.supplierproductmoddate = supplierproductmoddate;
    }
    public Date getSupplierproductmoddate() {
        return this.supplierproductmoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(supplierproductid);
        sb.append("|");
        sb.append(supplierproductProductid);
        sb.append("|");
        sb.append(supplierproductUserid);
        sb.append("|");
        sb.append(supplierproductSupplierid);
        sb.append("|");
        sb.append(supplierproductisactive);
        sb.append("|");
        sb.append(supplierproductmoddate);
        return sb.toString(); 
    } 


}
