/*
 * Created on 6 Dec 2015 ( Time 04:13:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Useraccess implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 255 )
    private String userid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 255 )
    private String userUserid;

    @Size( max = 100 )
    private String usercode;

    @Size( max = 100 )
    private String username;


    private Date usermoddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUserid( String userid ) {
        this.userid = userid ;
    }

    public String getUserid() {
        return this.userid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserUserid( String userUserid ) {
        this.userUserid = userUserid;
    }
    public String getUserUserid() {
        return this.userUserid;
    }

    public void setUsercode( String usercode ) {
        this.usercode = usercode;
    }
    public String getUsercode() {
        return this.usercode;
    }

    public void setUsername( String username ) {
        this.username = username;
    }
    public String getUsername() {
        return this.username;
    }

    public void setUsermoddate( Date usermoddate ) {
        this.usermoddate = usermoddate;
    }
    public Date getUsermoddate() {
        return this.usermoddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(userid);
        sb.append("|");
        sb.append(userUserid);
        sb.append("|");
        sb.append(usercode);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(usermoddate);
        return sb.toString(); 
    } 


}
