/*
 * Created on 6 Dec 2015 ( Time 04:13:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package tristi.general.web;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
